### ISSUE TITLE
[META] Tracking issue for EFB implementation

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/efb#1]
This tracks what needs to be done for the EFB to be in game

- [x] Pre-design
    - [x] Discussion of wanted functionality
    - [x] Initial poll, collection of ideas from community
    - [x] Second poll
- [ ] Design
    - [x] Model design
    - [x] UI concepts
    - [ ] Page designs
- [ ] Programming
    - [ ] Frontend
         - [ ] React integration
    - [ ] Backend
        - [ ] *TBA*
- [x] Integration
    - [x] Get model into game (blocked by exporter)
    - [x] Have UI render in game
    - [ ] Communicate with sim
